### ISSUE TITLE
Substitutions for special characters and numerals

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-reconciler#4]
The string matching algorithm at the moment distinguishes between special or accented characters and plain characters, so "Dong Son" for the Vietnamese period will return different results from "Dông Son" (or one will return none). Can we make a basic character substitution map so that special or accented characters match plaintext, or is this too complicated with Unicode?

On a related note, I would suggest that we definitely make the less complicated substitution map between Arabic and Roman numerals, so that "Early Bronze Age 2" returns possible matches in the form "Early Bronze Age II". This will increase recall without creating a lot of false positives, especially if we only substitute between numbers from 1-10 (or at most 1-20 -- no one has phase numbering beyond 20, though you will sometimes see a XII or so).

**Comment by ptgolden** [comment]
> Can we make a basic character substitution map so that special or accented characters match plaintext, or is this too complicated with Unicode?

https://www.npmjs.com/package/normalize-strings

**Comment by atomrab** [comment]
Well, there we go.

**Comment by ryanfb** [comment]
Another way to do this is to normalize input to Unicode NFD (decomposed) and then use a regex to strip all accent class characters (in Ruby this is `\p{M}`).

**Comment by ptgolden** [comment]
Yep, that's probably a better approach than relying on a whitelist of characters.

**Comment by ptgolden** [comment]
Fixed by 48d5efdc351689898db79f51c610b617919ce423

**Comment by ptgolden** [comment]
One issue with replacing Roman numerals with their Arabic equivalents is that the same processing is applied to both period labels and queries. Doing that replacement on a period label is no problem, since it's very unlikely that there would be a stray "I" "V" or "X" token appearing in a period label that was not a Roman numeral. However, there might be a situation where that would be the case in a query-- like if someone wanted all the periods that started with a "V". That's not a real case, but it's not far from one.

**Comment by atomrab** [comment]
But this comment is more about free-text searching than reconciliation, right? I would assume that one wouldn't have a dataset for reconciliation that just had letters like 'V' that weren't numerals.

**Comment by ptgolden** [comment]
Yes, you're right. Implemented in #7 if @rybesh is fine with it!
